# Generated by Django 6.0.3 on 2026-08-20 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emp_no', models.IntegerField()),
                ('emp_name', models.CharField(max_length=100)),
                ('emp_address', models.CharField(max_length=500)),
                ('emp_phonenumber', models.IntegerField()),
                ('emp_title', models.CharField(max_length=100)),
            ],
        ),
    ]
