# Generated by Django 6.0.3 on 2026-07-11 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='collegeStudents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('studentid', models.IntegerField()),
                ('studentname', models.CharField(max_length=30)),
                ('studentdept', models.CharField(max_length=30)),
            ],
        ),
    ]
