# Generated by Django 6.0.3 on 2026-08-17 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userLoginApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='dept',
            field=models.CharField(choices=[('IT', 'IT'), ('DATA_SOLUTIONS', 'Data Solutions'), ('ERP', 'ERP'), ('TESTING', 'Testing'), ('SOFTWARE_DEV', 'Software Development')], default='IT', max_length=50),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
